pages/components/Home/Events/PreviousEventCard.tsx, pages/components/Home/Events/UpcomingEventCard.tsx, pages/index.tsx, pages/leaderboard.tsx
can't find proper animation. Apart from that all set @Rajdip019
=> animation pending

pages/admin/add-event.tsx, pages/admin/edit-events.tsx
=> error resolved on admin

pages/components/Home/Events/UpcomingEventCard.tsx
@Rajdip019 diffrent eventcard issue resolved
=> admin eventCard Issue fixed

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Closes: #181 
Created an issue template for the repository to encourage easy contribution.
Created two readme files for the issue template i.e bug_report and feature_request.
=> Fix: Added Issue and Pull Request Template

pages/components/Hacktoberfest/Clueless_Hacktoberfest.tsx, pages/components/Hacktoberfest/Contribute.tsx, pages/components/Hacktoberfest/Guidelines.tsx
Fixed 3 Spacing Issues in the Hacktoberfest page
=> Hacktoberfest Page UI Fixes

CONTRIBUTING.md, pages/components/Hacktoberfest/ProjectCard.tsx
At projectCard.tsx line 20
-modified md:justify-start to md:justify-center
-added lg:justify-start
=> tech stack icons center aligned for screens 768px  to 1024px

pages/components/Hacktoberfest/RewardsAndPerks.tsx
The list bullets were overlapping with the image, adding some margin on the left will avoid this issue.
=> Update RewardsAndPerks.tsx UI

CONTRIBUTING.md, helpers/template.ts, package-lock.json, package.json, pages/components/Profile/Admin/AddProject.tsx, pages/components/Profile/Admin/EditProject.tsx, pages/components/Profile/Admin/ProjectsCardAdmin.tsx, pages/components/Profile/Admin/RemoveProject.tsx, pages/components/Profile/ProjectsCard.tsx, pages/components/shared/StyledChip.tsx, pages/components/shared/TechStackAutoComplete.tsx, pages/profile/[uid].tsx, pages/profile/admin/[uid]/index.tsx, tailwind.config.js
@Rajdip019
Would something like that work?
I think all the cards need more work on the breakpoints (but not sure if this should be done in this issue since the problem didn't originate here)
=> ProjectsCardAdmin redesign

pages/components/Profile/Admin/AddProject.tsx
Enhanced the UI of the Add Project section, according to the Figma design.
---
Fixes #170 
---
---
=> enh: Enhance UI of Add Project section

pages/contact-us/index.tsx
Fixed validations for contact us form.
---
Fixes #164 
---
---
=> Fixed Validations for Contact Us form

README.md
Added contributors section
---
Fixes #254 
---
---
=> Added Contributors section

pages/components/Hacktoberfest/Swags.tsx
Hi, I have completed working on issue #234. I have added the 'steps' for getting swags as discussed with @Debajyoti14 . Also made some UI changes to match the theme of the main website. This is responsive as well.
Here is an attached screenshot:
Please let me know if any changes are to be made. If everything is okay, kindly merge my PR.
Thank you,
Abir Santra
---
Fixes #234 
---
---
=> Improved 'How to get Swags' section

pages/components/shared/Footer.tsx
Change url for events for the path `https://www.clueless.tech/events`
---
Fixes #([Issue 313](https://github.com/Clueless-Community/clueless-official-website/issues/313))
---
---
=> fix-url-path-footer

pages/index.tsx
Added <a> links for sponsors.
---
Fixes #305 
---
---
=> added <a> links for sponsors

pages/components/AboutUS/ProfileCard.tsx
Added a scale-up hover animation to the contributors card + hover on socials
---
Fixes #306 
---
---
=> added contributors hover

pages/_app.tsx, pages/components/shared/Navbar/ModeSelect.tsx
- Removed the `system` option from the toggle.
- made the default theme light by setting `enableSystem={false}` in `ThemeProvider`
---
Fixes #346
=> removed system option from toggle & made light theme as default

pages/components/Home/Hacktoberfest.tsx
Changed The background color for HacktoberFest Component to bg-neutral-800
---
Fixes #341 
---
---
=> Changed Hacktoberfest's Background Color for Dark theme.

pages/components/shared/Footer.tsx
=> added Link to footer logo

pages/components/shared/Footer.tsx, pages/hacktoberfest/leaderboard.tsx
=> added Searchbar

package-lock.json, package.json, pages/index.tsx
I have added tooltips for Community Partners images which are shown on hovering over them.
---
Fixes #369 
---
---
=> Added Tooltips for Community Partners images

pages/hacktoberfest/leaderboard.tsx
Fixed leaderboard for dark mode.
---
Fixes #316 
---
---
=> Leaderboard Fixes for Dark Mode

pages/hacktoberfest/leaderboard.tsx
Fixed Leaderboard search input for dark mode
---
Fixes #378 
---
---
=> Fixed Leaderboard search input for dark mode

pages/hacktoberfest/leaderboard.tsx
Added the clear search button in leaderboard section.
---
Fixes #368 
---
---
=> clear search button added

pages/profile/[uid].tsx, pages/profile/admin/[uid]/index.tsx
=> Solved the background issue in the profile page for dark theme

pages/profile/admin/[uid]/edit.tsx
Added a loader while saving details in Profile screen
https://user-images.githubusercontent.com/74665996/198018190-b82888f8-ef66-4162-84fe-417d089db3a2.mp4
---
Fixes #394 
---
---
=> style: Add a loader while saving details in Profile screen

pages/_document.tsx, pages/about-us/index.tsx, pages/components/Home/HomeMain.tsx, pages/components/shared/Navbar/Navbar.tsx, pages/hacktoberfest/index.tsx, pages/profile/[uid].tsx
Fixed UI issue in issue #391 and added cdn of the scroll to top button to the _document.tsx instead of writing in the head tag of each page.
https://nextjs.org/docs/messages/no-stylesheets-in-head-component
---
Fixes #391 
---
---
=> Fixed UI error in the visitor's view of profile and updated _document.tsx

pages/faq/index.tsx
Fixed FAQ Accordian for Dark Mode
---
Fixes #315 
---
---
=> Fixed FAQ Accordian for Dark Mode

pages/components/Profile/Admin/AddProject.tsx
Fixed Add project section for dark theme
---
Fixes #398 
---
---
=> Fixed Add project section for dark theme

pages/components/shared/Navbar/NavbarAvatarDropDown.tsx
fixed alignment issue of Avatar initials
---
Fixes #407
---
---
=> fixed alignment issue of Avatar initials

pages/components/Profile/Admin/AddProject.tsx
Fixed UI of add project section in dark mode
---
Fixes #413 
---
---
=> fixed UI of add project in dark mode

pages/hacktoberfest/leaderboard.tsx
Now the clear shows only if the search box isn't null
---
Fixes #428 
@Debajyoti14 @Rajdip019
=> clear button is now based on search

pages/components/shared/Navbar/ModeSelect.tsx
Fixed Navbar issue. Also, i think there is no need to reposition it as it seems perfect in mobile view too and also after logged in.I have attached all ss below.
---
Fixes #432 
---
---
=> Navbar fix

pages/components/Profile/Admin/EditProject.tsx, pages/components/Profile/Admin/RemoveProject.tsx
Fix for Issue 414
Fixed the icons dark mode issue for #414 . Now the icons show up correctly in Light & dark mode both.
---
#414 
---
- [] New feature (non-breaking change which adds functionality)
---
=> Fix Icon colours in Profile Project Card -Issue #414

pages/components/shared/Navbar/ModeSelect.tsx, pages/components/shared/Navbar/Navbar.tsx
Fixed the Navbar breaking issue 
---
Fixes #[444](https://github.com/Clueless-Community/clueless-official-website/issues/444)
---
---
RIBUTING.md](/CONTRIBUTING.md)
https://user-images.githubusercontent.com/109169835/206032943-82ab66b3-db42-4067-96a5-b37fe00fe9f3.mp4
=> navbar responsive issue fixed

pages/components/shared/Navbar/ModeSelect.tsx, styles/Mui-styles/MenuStyle.Mui..ts
Changes the colour of menu in dark mode
---
Fixes #448 
---
---
=> Change Theme toggle dropdown colour in Dark Mode

database/techstacks.ts
---
Fixes #(issue_number)
---
---
=> multiple oracle from techstack-issues resolved

pages/profile/admin/[uid]/edit.tsx
=> dropdown colour change

pages/profile/admin/[uid]/edit.tsx
Reverts Clueless-Community/clueless-official-website#465
=> Dropdown colour haven't changed

pages/components/Home/Codepeak.tsx
Created the Codepeak banner for homepage. Left-aligned the content part as requested.
Desktop:
Tab:
Mobile:
Desktop:
Tablet:
Mobile:
---
Fixes #447 
---
---
=> Created Codepeak banner

pages/components/Home/HomeMain.tsx, styles/globals.css
---
Fixes #(issue_number)
---
---
=> updated the animations

package-lock.json, package.json, pages/components/home/Copilot/Copilot.tsx, pages/components/home/Copilot/go.tsx, pages/components/home/Copilot/js.tsx, pages/components/home/Copilot/py.tsx, pages/components/home/events/UpcomingEventCard.tsx, pages/components/home/events/UpcomingEvents.tsx, pages/index.tsx, styles/globals.css, styles/theme.ts
Revamped Tutorial Hell Section
---
Fixes #(i502)
---
---
=> Revamped Tutorial Hell Section

pages/components/home/WhatIsClueless/WhatIsClueless.tsx, pages/index.tsx
=> Closes #503 [`What is Clueless`]

package-lock.json, package.json, pages/components/home/HeroSection/HeroSection.tsx, pages/components/home/HeroSection/NavBar.tsx, pages/components/home/Tutorial Hell/go.tsx, pages/components/home/Tutorial Hell/js.tsx, pages/components/home/Tutorial Hell/py.tsx, pages/components/home/Tutorial Hell/tutorial_hell.tsx, pages/components/home/WorldOfOpenSource/WorldOfOpenSource.tsx, pages/index.tsx
=> Closes #493 `new/HeroSection`

components/home/TeamSection/Team.tsx, components/home/TeamSection/TeamMember.tsx, package-lock.json, package.json, pages/index.tsx
=> Team Section in home page added

components/home/TeamSection/TeamMember.tsx, styles/globals.css
See the changes https://www.loom.com/share/ed0d50827fd34a5590a5dccf0bbcd524
=> Scroll Smooth added in team section

pages/faq.tsx
issue-no
---
Fixes #(issue_number)
---
---
=> FAQ CTA and image fixed

components/home/Testimonials/testimonials.tsx, package-lock.json
=> Fixed the lagging issue while scrolling in testiminial section

components/home/HeroSection/PcHeroSection.tsx, components/home/TeamSection/TeamMember.tsx, components/home/WorldOfOpenSource/WorldOfOpenSource.tsx, database/membersData.ts, database/teamMembers.ts, pages/about-us.tsx
For Issue #572 
- Hero Section `Clueless Cummunity` & `Learn Grow` cursor deafult added
- World of Open source heading width issue fixed for Tablet devices
- About Us Our vision div mt increased because earlier it was overlapping the green line 
- Updated my github profile link
- team section animation made smooth and turned it on for mobile devices too
=> minor changes

components/home/HeroSection/PcHeroSection.tsx, package-lock.json
Reduced the map samples and rotation speed
=> Ravindra lag issue

CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, package-lock.json, package.json, pages/_app.tsx
Files Restored:- 
- Readme Restored
- Contribution.md 
- Code of Conduct
- MIT Licence
=> Readme Restored
